[env]
_.file = ".env"
CGO_ENABLED = "0"

[tools]
go = "1.26"
staticcheck = "latest"
fnox = "latest"

[vars]
filename = 'uptime'

[tasks.default]
description = "Execute the app in development mode"
depends = ["build"]
run = ["./{{vars.filename}}"]

[tasks.build]
description = "Execute the app in development mode"
depends = ["dependencies", "test", "lint"]
run = ["go build -o ./{{vars.filename}}"]

[tasks.dependencies]
description = "Download binary dependencies"
run = ["go mod download"]

[tasks.test]
description = "Unit tests"
depends = ["dependencies"]
env.DEV = "false"
run = ["go test -covermode=atomic -cover ./..."]

[tasks.lint]
depends = ["dependencies"]
run = ["go vet ./...", "staticcheck ./..."]
